name: netflix_ui
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  video_player: ^2.2.11
  flutter_bloc: ^8.0.1
  iconsax: ^0.0.8
  device_preview: ^1.0.0
  flutter_screenutil: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/web/
    - assets/images/web/top/
    - assets/images/web/preview/
    - assets/images/mobile/
    - assets/images/mobile/top/
    - assets/icons/
    - assets/thumbnail/
    - assets/video/
